import path from 'path';
import { writeFile, ensureDir } from '../utils/file';

interface ProjectOptions {
  architecture: string;
  framework: string;
  database: string;
  orm: string;
}

export const generateProject = async (
  projectName: string,
  basePath: string,
  options: ProjectOptions
): Promise<void> => {
  const projectPath = path.join(basePath, projectName);

  // Create base directory structure
  const dirs = [
    'src/domain/shared',
    'src/application',
    'src/infrastructure/database',
    'src/infrastructure/repositories',
    'src/infrastructure/messaging',
    'src/infrastructure/services',
    'src/presentation/http/controllers',
    'src/presentation/http/routes',
    'src/presentation/http/middlewares',
    'src/shared/constants',
    'src/shared/errors',
    'src/shared/utils',
    'src/container',
  ];

  for (const dir of dirs) {
    await ensureDir(path.join(projectPath, dir));
  }

  // package.json
  await writeFile(
    path.join(projectPath, 'package.json'),
    JSON.stringify(
      {
        name: projectName,
        version: '0.1.0',
        description: `${projectName} — generated by ArchGen`,
        main: 'dist/main.js',
        scripts: {
          build: 'tsc',
          start: 'node dist/main.js',
          dev: 'ts-node-dev src/main.ts',
          test: 'jest',
          'test:watch': 'jest --watch',
        },
        dependencies: {
          ...(options.framework === 'express'
            ? { express: '^4.18.2', cors: '^2.8.5', 'express-async-errors': '^3.1.1' }
            : options.framework === 'fastify'
            ? { fastify: '^4.25.2', '@fastify/cors': '^9.0.1' }
            : {}),
          ...(options.orm === 'prisma'
            ? { '@prisma/client': '^5.8.0' }
            : options.orm === 'typeorm'
            ? { typeorm: '^0.3.19', 'reflect-metadata': '^0.2.1' }
            : options.orm === 'drizzle'
            ? { 'drizzle-orm': '^0.29.3' }
            : {}),
          uuid: '^9.0.0',
        },
        devDependencies: {
          typescript: '^5.3.3',
          'ts-node': '^10.9.2',
          'ts-node-dev': '^2.0.0',
          '@types/node': '^20.11.0',
          ...(options.framework === 'express'
            ? { '@types/express': '^4.17.21', '@types/cors': '^2.8.17' }
            : {}),
          jest: '^29.7.0',
          '@types/jest': '^29.5.11',
          'ts-jest': '^29.1.2',
          ...(options.orm === 'prisma' ? { prisma: '^5.8.0' } : {}),
        },
      },
      null,
      2
    )
  );

  // tsconfig.json
  await writeFile(
    path.join(projectPath, 'tsconfig.json'),
    JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2020',
          module: 'commonjs',
          lib: ['ES2020'],
          outDir: 'dist',
          rootDir: 'src',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          resolveJsonModule: true,
          ...(options.orm === 'typeorm'
            ? { experimentalDecorators: true, emitDecoratorMetadata: true }
            : {}),
        },
        include: ['src/**/*'],
        exclude: ['node_modules', 'dist'],
      },
      null,
      2
    )
  );

  // main.ts
  await writeFile(
    path.join(projectPath, 'src', 'main.ts'),
    options.framework === 'express'
      ? `import 'express-async-errors';
import express from 'express';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Register routes here
// import { userRouter } from './presentation/http/routes/user.routes';
// app.use('/users', userRouter(userController));

// Error handler
app.use((err: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  console.error(err.stack);
  res.status(500).json({ message: err.message });
});

app.listen(PORT, () => {
  console.log(\`🚀 Server running on http://localhost:\${PORT}\`);
});
`
      : options.framework === 'fastify'
      ? `import Fastify from 'fastify';
import cors from '@fastify/cors';

const fastify = Fastify({ logger: true });

fastify.register(cors);

fastify.get('/health', async () => {
  return { status: 'ok', timestamp: new Date().toISOString() };
});

const start = async () => {
  try {
    await fastify.listen({ port: 3000 });
    console.log('🚀 Server running on http://localhost:3000');
  } catch (err) {
    fastify.log.error(err);
    process.exit(1);
  }
};

start();
`
      : `// NestJS — run: nest new ${projectName}
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
  console.log('🚀 NestJS app running on http://localhost:3000');
}
bootstrap();
`
  );

  // Shared error classes
  await writeFile(
    path.join(projectPath, 'src', 'shared', 'errors', 'AppError.ts'),
    `export class AppError extends Error {
  constructor(
    public readonly message: string,
    public readonly statusCode: number = 400,
    public readonly code?: string
  ) {
    super(message);
    this.name = 'AppError';
    Object.setPrototypeOf(this, AppError.prototype);
  }
}

export class NotFoundError extends AppError {
  constructor(resource: string, id: string) {
    super(\`\${resource} with id \${id} not found\`, 404, 'NOT_FOUND');
  }
}

export class ValidationError extends AppError {
  constructor(message: string) {
    super(message, 422, 'VALIDATION_ERROR');
  }
}

export class UnauthorizedError extends AppError {
  constructor() {
    super('Unauthorized', 401, 'UNAUTHORIZED');
  }
}
`
  );

  // Base entity
  await writeFile(
    path.join(projectPath, 'src', 'domain', 'shared', 'BaseEntity.ts'),
    `import { randomUUID } from 'crypto';

export abstract class BaseEntity {
  private readonly _id: string;
  private readonly _createdAt: Date;
  private _updatedAt: Date;

  constructor(id?: string) {
    this._id = id ?? randomUUID();
    this._createdAt = new Date();
    this._updatedAt = new Date();
  }

  get id(): string {
    return this._id;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  get updatedAt(): Date {
    return this._updatedAt;
  }

  protected touch(): void {
    this._updatedAt = new Date();
  }

  equals(other: BaseEntity): boolean {
    return this._id === other._id;
  }
}
`
  );

  // Base repository interface
  await writeFile(
    path.join(projectPath, 'src', 'domain', 'shared', 'IBaseRepository.ts'),
    `export interface IBaseRepository<T> {
  findById(id: string): Promise<T | null>;
  findAll(): Promise<T[]>;
  save(entity: T): Promise<void>;
  update(entity: T): Promise<void>;
  delete(id: string): Promise<void>;
}
`
  );

  // .env.example
  await writeFile(
    path.join(projectPath, '.env.example'),
    `PORT=3000
NODE_ENV=development
${options.database === 'postgres' ? 'DATABASE_URL=postgresql://user:password@localhost:5432/dbname' : ''}
${options.database === 'mysql' ? 'DATABASE_URL=mysql://user:password@localhost:3306/dbname' : ''}
${options.database === 'mongodb' ? 'MONGODB_URI=mongodb://localhost:27017/dbname' : ''}
`
  );

  // .gitignore
  await writeFile(
    path.join(projectPath, '.gitignore'),
    `node_modules/
dist/
.env
*.js.map
coverage/
`
  );

  // README.md
  await writeFile(
    path.join(projectPath, 'README.md'),
    `# ${projectName}

> Generated by [ArchGen](https://github.com/archgen) — Enterprise Architecture CLI

## Architecture

- **Pattern**: ${options.architecture.toUpperCase()}
- **Framework**: ${options.framework}
- **Database**: ${options.database}
- **ORM**: ${options.orm}

## Getting Started

\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`

## Project Structure

\`\`\`
src/
├── domain/        # Enterprise business rules (entities, value objects, events)
├── application/   # Application business rules (use cases, DTOs)
├── infrastructure/# Frameworks & drivers (DB, external services)
├── presentation/  # Delivery mechanism (HTTP controllers, routes)
├── shared/        # Cross-cutting concerns (errors, utils)
└── container/     # Dependency injection wiring
\`\`\`

## Commands

\`\`\`bash
# Generate a full module
archgen generate module <Name>

# Generate individual pieces
archgen generate domain <Name>
archgen generate usecase <Name>
archgen generate repository <Name>
archgen generate controller <Name>
\`\`\`
`
  );
};
