import path from 'path';
import { writeFile } from '../utils/file';
import { toPascalCase, toKebabCase, toCamelCase } from '../utils/file';

export const generateRepository = async (name: string, basePath: string): Promise<void> => {
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);
  const kebab = toKebabCase(name);

  // Domain interface (already generated by domain generator, but standalone here)
  await writeFile(
    path.join(basePath, 'src', 'domain', kebab, 'repositories', `I${pascal}Repository.ts`),
    `import { ${pascal} } from '../entities/${pascal}';

export interface I${pascal}Repository {
  findById(id: string): Promise<${pascal} | null>;
  findAll(): Promise<${pascal}[]>;
  save(${camel}: ${pascal}): Promise<void>;
  update(${camel}: ${pascal}): Promise<void>;
  delete(id: string): Promise<void>;
}
`
  );

  // Infrastructure implementation
  await writeFile(
    path.join(basePath, 'src', 'infrastructure', 'repositories', `${pascal}Repository.ts`),
    `import { ${pascal} } from '../../domain/${kebab}/entities/${pascal}';
import { I${pascal}Repository } from '../../domain/${kebab}/repositories/I${pascal}Repository';

/**
 * Concrete implementation of I${pascal}Repository.
 * Replace the in-memory store with your ORM (Prisma, TypeORM, Drizzle, Mongoose).
 */
export class ${pascal}Repository implements I${pascal}Repository {
  // Replace with actual DB client injection
  private store: Map<string, ${pascal}> = new Map();

  async findById(id: string): Promise<${pascal} | null> {
    return this.store.get(id) ?? null;
  }

  async findAll(): Promise<${pascal}[]> {
    return Array.from(this.store.values());
  }

  async save(${camel}: ${pascal}): Promise<void> {
    this.store.set(${camel}.id, ${camel});
  }

  async update(${camel}: ${pascal}): Promise<void> {
    if (!this.store.has(${camel}.id)) {
      throw new Error(\`${pascal} with id \${${camel}.id} not found\`);
    }
    this.store.set(${camel}.id, ${camel});
  }

  async delete(id: string): Promise<void> {
    this.store.delete(id);
  }
}
`
  );
};
